server:
  port: 8091
  contextPath: /sw-services

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: rainmaker_new
  sslmode: disable

pagination:
  defaultLimit: 50
  maxLimit: 500
  defaultOffset: 0

peers:
  mdmsHost: http://localhost:8094/
  mdmsSearchPath: egov-mdms-service/v1/_search
  propertyHost: https://dev.digit.org/
  propertySearchPath: property-services/property/_search
  idgenHost: http://localhost:8088/
  idgenGeneratePath: egov-idgen/id/_generate
  userHost: http://localhost:8081/
  userSearchPath: user/v1/_search
  userCreateNoValidatePath: user/users/_createnovalidate
